import Head from 'next/head';
import Input from '../components/Input/Input';
import SelectUser from '../components/SelectUser/SelectUser';
import TodoList from '../components/TodoList/TodoList';
import { Main, Content, Title } from '../components/index.styles';
import axios from 'axios';

export default function Home({ uniqueIds }) {
	

	return (
		<>
			<Head>
				<title>TODO App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Title>TODO APP</Title>
				<Content>
					<SelectUser usersId={uniqueIds} />
					<Input />
					<TodoList  />
				</Content>
			</Main>
		</>
	);
}

export async function getStaticProps() {
	// getting each unique userId on build
	const { data } = await axios('https://jsonplaceholder.typicode.com/todos');
	const usersId = data.map((todo) => todo.userId);
	const uniqueIds = [...new Set(usersId)];
	return {
		props: { uniqueIds },
	};
}
